tracer:
  property: "I AM THE DEFAULT"
spring:
  jpa:
    database: "POSTGRESQL"
    platform: "postgres"
    show-sql: "true"
    driverClassName: "org.postgresql.Driver"
    properties:
      hibernate:
        dialect:"org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    url: "jdbc:postgresql://database:5432/eagle_eye_local"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

